<a href="https://colab.research.google.com/github/SaravanavelE/Gender_Classification_using_Support_Vector_Machine/blob/main/gender_classification_using_support_vector_machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import export_graphviz

In [4]:
d = pd.read_csv("/content/drive/MyDrive/AI ML/2026/Technical/Datasets/gender_classification_v7.csv")
d

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,Male
1,0,14.0,5.4,0,0,1,0,Female
2,0,11.8,6.3,1,1,1,1,Male
3,0,14.4,6.1,0,1,1,1,Male
4,1,13.5,5.9,0,0,0,0,Female
...,...,...,...,...,...,...,...,...
4996,1,13.6,5.1,0,0,0,0,Female
4997,1,11.9,5.4,0,0,0,0,Female
4998,1,12.9,5.7,0,0,0,0,Female
4999,1,13.2,6.2,0,0,0,0,Female
5000,1,15.4,5.4,1,1,1,1,Male

In [5]:
d.head()

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,Male
1,0,14.0,5.4,0,0,1,0,Female
2,0,11.8,6.3,1,1,1,1,Male
3,0,14.4,6.1,0,1,1,1,Male
4,1,13.5,5.9,0,0,0,0,Female

In [6]:
d.tail()

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
4996,1,13.6,5.1,0,0,0,0,Female
4997,1,11.9,5.4,0,0,0,0,Female
4998,1,12.9,5.7,0,0,0,0,Female
4999,1,13.2,6.2,0,0,0,0,Female
5000,1,15.4,5.4,1,1,1,1,Male

In [7]:
d.isna().sum()

long_hair                    0
forehead_width_cm            0
forehead_height_cm           0
nose_wide                    0
nose_long                    0
lips_thin                    0
distance_nose_to_lip_long    0
gender                       0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x = d.drop("gender",axis = 1)
y = d["gender"]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((4000, 7), (1001, 7), (4000,), (1001,))

Linear

In [9]:
from sklearn.svm import SVC
model = SVC(kernel='linear')
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("accuracy_score:",accuracy_score(y_test,y_pred))
print("confusion_matrix :\n",confusion_matrix(y_test,y_pred))
print("classification_report :\n",classification_report(y_test,y_pred))

accuracy_score: 0.9690309690309691
confusion_matrix :
 [[477  21]
 [ 10 493]]
classification_report :
               precision    recall  f1-score   support

      Female       0.98      0.96      0.97       498
        Male       0.96      0.98      0.97       503

    accuracy                           0.97      1001
   macro avg       0.97      0.97      0.97      1001
weighted avg       0.97      0.97      0.97      1001

Sigmoid

In [10]:
from sklearn.svm import SVC
model = SVC(kernel='sigmoid')
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("accuracy_score:",accuracy_score(y_test,y_pred))
print("confusion_matrix :\n",confusion_matrix(y_test,y_pred))
print("classification_report :\n",classification_report(y_test,y_pred))

accuracy_score: 0.41358641358641357
confusion_matrix :
 [[228 270]
 [317 186]]
classification_report :
               precision    recall  f1-score   support

      Female       0.42      0.46      0.44       498
        Male       0.41      0.37      0.39       503

    accuracy                           0.41      1001
   macro avg       0.41      0.41      0.41      1001
weighted avg       0.41      0.41      0.41      1001

rbf

In [11]:
from sklearn.svm import SVC
model = SVC(kernel='rbf')
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("accuracy_score:",accuracy_score(y_test,y_pred))
print("confusion_matrix :\n",confusion_matrix(y_test,y_pred))
print("classification_report :\n",classification_report(y_test,y_pred))

accuracy_score: 0.972027972027972
confusion_matrix :
 [[486  12]
 [ 16 487]]
classification_report :
               precision    recall  f1-score   support

      Female       0.97      0.98      0.97       498
        Male       0.98      0.97      0.97       503

    accuracy                           0.97      1001
   macro avg       0.97      0.97      0.97      1001
weighted avg       0.97      0.97      0.97      1001

poly

In [12]:
from sklearn.svm import SVC
model = SVC(kernel='poly')
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("accuracy_score:",accuracy_score(y_test,y_pred))
print("confusion_matrix :\n",confusion_matrix(y_test,y_pred))
print("classification_report :\n",classification_report(y_test,y_pred))

accuracy_score: 0.97002997002997
confusion_matrix :
 [[473  25]
 [  5 498]]
classification_report :
               precision    recall  f1-score   support

      Female       0.99      0.95      0.97       498
        Male       0.95      0.99      0.97       503

    accuracy                           0.97      1001
   macro avg       0.97      0.97      0.97      1001
weighted avg       0.97      0.97      0.97      1001

In [13]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("accuracy_score:",accuracy_score(y_test,y_pred))
print("confusion_matrix :\n",confusion_matrix(y_test,y_pred))
print("classification_report :\n",classification_report(y_test,y_pred))

accuracy_score: 0.977022977022977
confusion_matrix :
 [[488  10]
 [ 13 490]]
classification_report :
               precision    recall  f1-score   support

      Female       0.97      0.98      0.98       498
        Male       0.98      0.97      0.98       503

    accuracy                           0.98      1001
   macro avg       0.98      0.98      0.98      1001
weighted avg       0.98      0.98      0.98      1001

In [14]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100,max_features=100)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("accuracy_score:",accuracy_score(y_test,y_pred))
print("confusion_matrix :\n",confusion_matrix(y_test,y_pred))
print("classification_report :\n",classification_report(y_test,y_pred))

accuracy_score: 0.9690309690309691
confusion_matrix :
 [[484  14]
 [ 17 486]]
classification_report :
               precision    recall  f1-score   support

      Female       0.97      0.97      0.97       498
        Male       0.97      0.97      0.97       503

    accuracy                           0.97      1001
   macro avg       0.97      0.97      0.97      1001
weighted avg       0.97      0.97      0.97      1001